#!/bin/bash

export LANG="en_US.UTF-8"
export PATH=$PATH:/usr/local/bin

cmd_name=$(echo $(basename "$0") | cut -d . -f1)

for hook in $(dirname "$0")/${cmd_name}.d/*; do
    bash ${hook} ${@:1}
    RESULT=$?
    if [[ ${RESULT} != 0 ]]; then
        echo "$hook returned non-zero: $RESULT, abort commit"
        exit ${RESULT}
    fi
done

exit 0